INSERT INTO game_items (id, type, name, category, description, stats, kit, buyable, validation_group, lock_criteria)
VALUES
	(1, 'appearance', 'Desert Battle Dress', 'uniform', 'SHARED_ASSAULT_Custom_Item_1_ShortDesc', NULL, -1, TRUE, NULL, 0),
	(3, 'appearance', 'Desert Tac-Com Helmet', 'head', 'SHARED_ASSAULT_Custom_Item_3_ShortDesc', NULL, -1, TRUE, NULL, 0),
	(4, 'appearance', 'Khaki Combat Pack', 'accessory1', 'SHARED_ASSAULT_Custom_Item_4_ShortDesc', NULL, -1, TRUE, NULL, 0),
	(5, 'appearance', 'Khaki tactical belt', 'accessory2', 'SHARED_ASSAULT_Custom_Item_5_ShortDesc', NULL, -1, TRUE, NULL, 0),
	(6, 'appearance', 'Woodland Combat Uniform', 'uniform', 'SHARED_ASSAULT_Custom_Item_6_ShortDesc', NULL, -1, TRUE, NULL, 0),
	(7, 'appearance', 'Land Ops Goggles', 'face', 'SHARED_ASSAULT_Custom_Item_7_ShortDesc', NULL, -1, TRUE, NULL, 0),
	(9, 'appearance', 'Woodland Vehicle Ops Helmet', 'head', 'SHARED_ASSAULT_Custom_Item_9_ShortDesc', NULL, -1, TRUE, NULL, 0),
	(11, 'appearance', 'Taiga Combat Pack', 'accessory1', 'SHARED_ASSAULT_Custom_Item_11_ShortDesc', NULL, -1, TRUE, NULL, 0),
	(12, 'appearance', 'Taiga Tactical Belt', 'accessory2', 'SHARED_ASSAULT_Custom_Item_12_ShortDesc', NULL, -1, TRUE, NULL, 0),
	(42, 'appearance', 'Tri-C Desert Battle Dress', 'uniform', 'SHARED_ASSAULT_Custom_Item_42_ShortDesc', NULL, -1, TRUE, NULL, 0),
	(43, 'appearance', 'Spectre SO Tactical Belt', 'accessory2', 'SHARED_ASSAULT_Custom_Item_43_ShortDesc', NULL, -1, TRUE, NULL, 0),
	(44, 'appearance', 'D-Tec Spec Ops Helmet', 'head', 'SHARED_ASSAULT_Custom_Item_44_ShortDesc', NULL, -1, TRUE, NULL, 0),
	(45, 'appearance', 'Spectre SO Combat Pack', 'accessory1', 'SHARED_ASSAULT_Custom_Item_45_ShortDesc', NULL, -1, TRUE, NULL, 0),
	(66, 'appearance', 'Partizan Oversuit', 'uniform', 'Partizan Oversuit', NULL, -1, TRUE, NULL, 0),
	(67, 'appearance', 'Maska 1Sch Helmet', 'head', 'SHARED_ASSAULT_Custom_Item_67_ShortDesc', NULL, -1, TRUE, NULL, 0),
	(68, 'appearance', 'D-Eye Balaclava', 'face', 'SHARED_ASSAULT_Custom_Item_68_ShortDesc', NULL, -1, TRUE, NULL, 0),
	(69, 'appearance', 'Alpha SP Pack', 'accessory1', 'SHARED_ASSAULT_Custom_Item_69_ShortDesc', NULL, -1, TRUE, NULL, 0),
	(70, 'appearance', 'Alpha SP Belt', 'accessory2', 'SHARED_ASSAULT_Custom_Item_70_ShortDesc', NULL, -1, TRUE, NULL, 0),
	(287, 'appearance', 'Covert Ops Com-Set Cap', 'head', 'Covert Ops Com-Set Cap', NULL, -1, TRUE, NULL, 0),
	(288, 'appearance', 'Covert Ops Shades', 'face', 'Desc', NULL, -1, TRUE, NULL, 0),
	(291, 'appearance', 'CAS G-Suit', 'uniform', 'CAS G-Suit', 'null', -1, TRUE, NULL, 0),
	(292, 'appearance', 'Pilot Helmet', 'head', 'Pilot Helmet', NULL, -1, TRUE, NULL, 0),
	(294, 'appearance', 'Urban Militia Combat Dress', 'uniform', 'Urban Militia Combat Dress', NULL, -1, TRUE, NULL, 0),
	(295, 'appearance', 'Militia Force Shemagh', 'face', 'Militia Force Shemagh', NULL, -1, TRUE, NULL, 0),
	(297, 'appearance', 'Beta Force Beret', 'head', 'Beta Force Beret', NULL, -1, TRUE, NULL, 0),
	(298, 'appearance', 'World Force Beret', 'head', 'World Force Beret', NULL, -1, TRUE, NULL, 0),
	(305, 'appearance', 'Elite Assault Cap', 'head', 'Elite Assault Cap', NULL, -1, TRUE, NULL, 0),
	(306, 'appearance', 'Elite Assault Gear', 'uniform', 'Elite Assault Gear', NULL, -1, TRUE, NULL, 0),
	(307, 'appearance', 'Elite Assault Shades', 'face', 'Shades', NULL, -1, TRUE, NULL, 0),
	(308, 'appearance', 'Elite Assault Combat Holster', 'accessory2', 'Elite Assault Combat Holster', NULL, -1, TRUE, NULL, 0),
	(309, 'appearance', 'Elite Assault Load Carrier', 'accessory2', 'Elite Assault Load Carrier', NULL, -1, TRUE, NULL, 0),
	(312, 'appearance', 'Battle Surgeon''s Pack', 'accessory1', 'Battle Surgeon''s Pack', NULL, -1, TRUE, NULL, 0),
	(313, 'appearance', 'Battle Surgeon''s Triage Kit', 'accessory2', 'Battle Surgeon''s Triage Kit', NULL, -1, TRUE, NULL, 0),
	(314, 'appearance', 'No Head Cloth', 'head', 'Alternative to having no helmet', NULL, -1, TRUE, NULL, 0),
	(315, 'appearance', 'German Desert Camo Helmet', 'head', '', NULL, -1, TRUE, NULL, 0),
	(316, 'appearance', 'German Desert Camo Uniform', 'uniform', 'German Desert Camo Uniform', NULL, -1, TRUE, NULL, 0),
	(317, 'appearance', 'German Desert Camo Pack', 'accessory1', 'German Desert Camo Pack', NULL, -1, TRUE, NULL, 0),
	(318, 'appearance', 'German Desert Camo Belt', 'accessory2', 'German Desert Camo Belt', NULL, -1, TRUE, NULL, 0),
	(319, 'appearance', 'Polish Desert Camo Helmet', 'head', '', NULL, -1, TRUE, NULL, 0),
	(320, 'appearance', 'Polish Desert Camo Uniform', 'uniform', 'Partizan Oversuit', NULL, -1, TRUE, NULL, 0),
	(321, 'appearance', 'Polish National Pouches', 'accessory1', 'Polish National Pouches', NULL, -1, TRUE, NULL, 0),
	(322, 'appearance', 'Polish National Belt', 'accessory2', 'Desc', NULL, -1, TRUE, NULL, 0),
	(323, 'appearance', 'French Desert Camo Helmet', 'head', '', NULL, -1, TRUE, NULL, 0),
	(324, 'appearance', 'French Desert Camo Uniform', 'uniform', 'French Desert Camo Uniform', NULL, -1, TRUE, NULL, 0),
	(325, 'appearance', 'French Desert Camo Pack', 'accessory1', 'Desc', NULL, -1, TRUE, NULL, 0),
	(326, 'appearance', 'French Desert Camo Belt', 'accessory2', 'French Desert Camo Belt', NULL, -1, TRUE, NULL, 0),
	(328, 'appearance', 'US Universal Digital Uniform', 'uniform', 'Partizan Oversuit', NULL, -1, TRUE, NULL, 0),
	(329, 'appearance', 'US National Pouches', 'accessory1', 'Desc', NULL, -1, TRUE, NULL, 0),
	(330, 'appearance', 'US National Belt', 'accessory2', 'Desc', NULL, -1, TRUE, NULL, 0),
	(331, 'appearance', 'Russian Desert Digital Helmet', 'head', '', NULL, -1, TRUE, NULL, 0),
	(332, 'appearance', 'Russian Desert Digital Uniform', 'uniform', 'Partizan Oversuit', NULL, -1, TRUE, NULL, 0),
	(333, 'appearance', 'Russian Desert Digital Pack', 'accessory1', 'Russian Desert Digital Pack', NULL, -1, TRUE, NULL, 0),
	(334, 'appearance', 'Russian Desert Digital Belt', 'accessory2', 'Russian Desert Digital Belt', NULL, -1, TRUE, NULL, 0),
	(335, 'appearance', 'Tank Driver Helmet', 'head', 'Tank Driver Helmet', NULL, -1, TRUE, NULL, 0),
	(336, 'appearance', 'Tank Driver`s Uniform', 'uniform', '', NULL, -1, TRUE, NULL, 0),
	(337, 'appearance', 'Tank drivers shades', 'face', 'Tank drivers shades', NULL, -1, TRUE, NULL, 0),
	(338, 'appearance', 'Combat Engineer''s Welding Helmet', 'head', 'Combat Engineer''s Welding Helmet', NULL, -1, TRUE, NULL, 0),
	(339, 'appearance', 'Engineer Uniform', 'uniform', 'Engineer Uniform', NULL, -1, TRUE, NULL, 0),
	(340, 'appearance', 'Enginner Pouches', 'accessory1', 'Desc', NULL, -1, TRUE, NULL, 0),
	(341, 'appearance', 'Engineer Tools', 'accessory2', 'Desc', NULL, -1, TRUE, NULL, 0),
	(342, 'appearance', 'Santa Hat', 'head', 'Santa Hat', NULL, -1, TRUE, NULL, 0),
	(343, 'appearance', 'Half Skull Balaclava', 'face', 'Desc', NULL, -1, TRUE, NULL, 0),
	(344, 'appearance', 'Santa Combat Hat', 'head', 'Santa Combat Hat', NULL, -1, TRUE, NULL, 0),
	(345, 'appearance', 'Santa Balaclava', 'face', 'Shades', NULL, -1, TRUE, NULL, 0),
	(346, 'appearance', 'JokerSmile Balaclava', 'face', 'Desd', NULL, -1, TRUE, NULL, 0),
	(347, 'appearance', 'Stitched Balaclava', 'face', 'Stitched Balaclava', NULL, -1, TRUE, NULL, 0),
	(348, 'appearance', 'Skull Balaclava', 'face', 'Skull Balaclava', NULL, -1, TRUE, NULL, 0),
	(356, 'appearance', 'Server Ops Beret', 'head', 'Server Ops Beret', NULL, -1, TRUE, NULL, 0),
	(358, 'appearance', 'One Year Uniform', 'uniform', 'Desc', NULL, -1, TRUE, NULL, 0),
	(360, 'appearance', 'Ambush Jungle Fighter Boonie Hat', 'head', 'Ambush Jungle Fighter Boonie Hat', NULL, -1, TRUE, NULL, 0),
	(361, 'appearance', 'Ambush Jungle Fighter Uniform', 'uniform', 'Ambush Jungle Fighter Uniform', NULL, -1, TRUE, NULL, 0),
	(363, 'appearance', 'Jungle face Paint', 'face', 'Shades', NULL, -1, TRUE, NULL, 0),
	(364, 'appearance', 'US Marine Veteran Outfit', 'uniform', 'US Marine Veteran Outfit', NULL, -1, TRUE, NULL, 0),
	(365, 'appearance', 'German Kommando Veteran Outfit', 'uniform', 'German Kommando Veteran Outfit', NULL, -1, TRUE, NULL, 0),
	(366, 'appearance', 'Brazilian SpecOps Veteran Outfit', 'uniform', 'Brazilian SpecOps Veteran Outfit', NULL, -1, TRUE, NULL, 0),
	(367, 'appearance', 'Italian Alpini Veteran Outfit', 'uniform', 'Italian Alpini Veteran Outfit', NULL, -1, TRUE, NULL, 0),
	(368, 'appearance', 'Russian Spetsnaz Veteran Outfit', 'uniform', 'Russian Spetsnaz Veteran Outfit', NULL, -1, TRUE, NULL, 0),
	(369, 'appearance', 'French Legionary Veteran outfit', 'uniform', 'French Legionary Veteran outfit', NULL, -1, TRUE, NULL, 0),
	(370, 'appearance', 'Belgian Para Veteran Outfit', 'uniform', 'Belgian Para Veteran Outfit', NULL, -1, TRUE, NULL, 0),
	(371, 'appearance', 'British Special Forces Veteran Outfit', 'uniform', 'British Special Forces Veteran Outfit', NULL, -1, TRUE, NULL, 0),
	(372, 'appearance', 'Swedish Ranger Veteran Outfit', 'uniform', 'Swedish Ranger Veteran Outfit', NULL, -1, TRUE, NULL, 0),
	(373, 'appearance', 'Polish Special Forces veteran Outfit', 'uniform', 'Polish Special Forces veteran Outfit', NULL, -1, TRUE, NULL, 0),
	(2004, 'abilities', 'Medic Box', 'gadget', 'I should probably add this -LifeCoder', NULL, 2, FALSE, 'gadget', 0),
	(2005, 'abilities', 'Frag Grenade', 'gadget', 'Fragmentation Grenade having a large \"casualty radius\". It is ideal for urban operations and close quarters combat. It allows infantry to engage targets with in-direct fire.', NULL, -1, FALSE, 'gadget', 0),
	(2009, 'abilities', 'Front Line Flare', 'gadget', 'I should probably add this -LifeCoder', NULL, 2, FALSE, 'gadget', 0),
	(2017, 'abilities', 'Motion Sensor', 'gadget', 'Motion Sensor', NULL, 0, TRUE, 'gadget', 0),
	(2021, 'abilities', 'Vehicle Repair Tool', 'gadget', 'Vehicle Repair Tool', NULL, 3, TRUE, 'gadget', 0),
	(2023, 'abilities', 'Ammo Box', 'gadget', 'This box contains extra ammunition for all weapons on the battlefield.', NULL, 1, FALSE, 'gadget', 0),
	(2024, 'abilities', 'Request Reinforcements', 'gadget', 'Requests reinforcements', NULL, 1, TRUE, 'gadget', 0),
	(2025, 'abilities', 'Mortar Strike', 'gadget', 'Mortar Strike', NULL, 0, TRUE, 'gadget', 0),
	(2030, 'abilities', 'Combat Defibrillator', 'gadget', 'This unit uses a high voltage shock to revive critically wounded teammates.  The electric discharge from the Defib can also be used to kill enemies in close quarter situations.', NULL, 2, FALSE, 'gadget', 0),
	(2034, 'abilities', 'C4 Charges', 'gadget', 'C4 Charges', NULL, 1, TRUE, 'gadget', 0),
	(2046, 'abilities', 'Anti-Vehicle Mine', 'gadget', 'Anti-Vehicle Mine', NULL, 3, TRUE, 'gadget', 0),
	(2048, 'abilities', 'Claymore', 'gadget', 'Claymore', NULL, 0, TRUE, 'gadget', 0),
	(2050, 'abilities', 'Smoke Grenade', 'gadget', 'Smoke Grenade', NULL, 1, TRUE, 'gadget', 0),
	(2051, 'abilities', 'XM25 Airburst Genade Launcher', 'gadget', 'XM25 Airburst Genade Launcher', NULL, 3, TRUE, 'gadget', 0),
	(2054, 'abilities', 'Anti-Vehicle RPG', 'gadget', 'Anti-Vehicle RPG', NULL, 3, TRUE, 'gadget', 0),
	(2168, 'abilities', 'Tracer Dart', 'gadget', 'This weapon uses pressurized gas to fire a dart with a miniature homing beacon built in. When this dart strikes enemy vehicles, missiles from RPGs fired at that vehicle will home-in on the beacon.', NULL, -1, FALSE, 'gadget', 0),
	(3000, 'weapons', '870 Combat', 'shotgun', 'The 870 Modular Combat Shotgun is a rugged, powerful shotgun ideal in CQB (close quarter battle) where breaching and stopping power is critical. The 870 can be configured for multi-mission roles allowing various ammunition combinations.', NULL, -1, TRUE, 'primary', 0),
	(3001, 'weapons', 'M16A2', 'assault_rifle', 'This version of the classic Gadget has a 3-round burst and a large magazine providing with great fire endurance.', NULL, 1, TRUE, 'primary', 0),
	(3003, 'weapons', 'M249 SAW', 'lmg', 'Based on the Belgian Minimi, the M249 is a standard issue squad automatic weapon in the US Army. It''s very accurate and provides great fire on target capabilities.', NULL, 2, TRUE, 'primary', 0),
	(3004, 'weapons', 'SV-98', 'sniper_rifle', 'Some kind of sniper', NULL, 0, TRUE, 'primary', 0),
	(3005, 'weapons', 'G3A4', 'assault_rifle', 'This German made battle rifle is the default weapon for the Assault class.', NULL, 1, FALSE, 'primary', 0),
	(3006, 'weapons', 'M9', 'pistol', '9mm semi-automatic gadget which has served as the gadget gadget in the US military. Equipped with a 15 round staggered magazine with reversible release. An optimal level of mobility accounts for considerable lack of power. Capable of being modified to support lights and other tools.', NULL, -1, FALSE, 'secondary', 0),
	(3007, 'weapons', 'AEK-971', 'assault_rifle', 'The AEK-971 assault rifle has great damage dealing potential, especially over shorter ranges.', NULL, 1, TRUE, 'primary', 0),
	(3008, 'weapons', 'SPAS-12', 'shotgun', 'Designed for police and military applications, the SPAS-12 is a versatile and reliable pump action shotgun. It has been in service for over 37 years and is still a favorite among special ops.', NULL, -1, TRUE, 'primary', 0),
	(3011, 'weapons', 'SCAR-L', 'assault_rifle', 'Designed for the needs of US Special Forces, the SCAR is great all-round assault rifle with excellent precision characteristics.', NULL, 1, TRUE, 'primary', 0),
	(3012, 'weapons', 'UMP', 'smg', 'This version of the classic Gadget has a 3-round burst and a large magazine providing with great fire endurance', 'null', 3, TRUE, 'primary', 0),
	(3013, 'weapons', 'MG3', 'lmg', 'This German made light machine gun is the default weapon for the Medic class.', NULL, 2, FALSE, 'primary', 0),
	(3014, 'weapons', 'PKM', 'lmg', 'The Russian PKM is adopted worldwide for its rugged operation and reliability. It\\u2019s an excellent easy to use general purpose machine gun.', NULL, 2, TRUE, 'primary', 0),
	(3015, 'weapons', 'M60', 'lmg', 'Since its introduction in 1957 M60 has been the workhorse of every branch of the US Military. It is a stable, accurate and very heavy hitting machine gun.', NULL, 2, TRUE, 'primary', 0),
	(3018, 'weapons', 'PP-2000', 'smg', 'Basic engineer smg', NULL, 3, TRUE, 'primary', 0),
	(3019, 'weapons', 'M1911', 'pistol', 'A favorite sidearm among special forces this 7 round semi-automatic pistol boasts a .45 caliber stopping power, enabling the operator to dispose of an opponent with lethal close range fire.', NULL, -1, FALSE, 'secondary', 0),
	(3020, 'weapons', 'MP412 REX', 'pistol', 'A 6 round revolver revered for its close range edge and notable Magnum firepower. Its top break design is a throw back to old 6-shooters of the \"Wild West\".', NULL, -1, FALSE, 'secondary', 0),
	(3021, 'weapons', 'MP-443', 'pistol', 'Adopted as sidearm for all branches of the Russian military and law enforcement, this 17 round semi-automatic pistol boasts high mobility and operates with a short recoil.', NULL, -1, FALSE, 'secondary', 0),
	(3022, 'weapons', 'M95', 'sniper_rifle', 'The M95 is an improved version of the earlier Barrett M90. It is a bolt-action sniper rifle in a bullpup design.', NULL, 0, FALSE, 'primary', 0),
	(3023, 'weapons', 'SVD', 'sniper_rifle', 'Widely used in the former Warsaw pact countries with an effective range of 800 metres,', NULL, 0, FALSE, 'primary', 0),
	(3024, 'weapons', 'M24', 'sniper_rifle', 'Originally designed to use the .30-06 Magnum cartridge the rifle was eventually re-chambered to use 7.62mm NATO round. This however did not detract from the range or the stopping power as the M24 still proves popular with snipers worldwide.', NULL, 0, FALSE, 'primary', 0),
	(3025, 'weapons', 'SAIGA-12', 'shotgun', 'A Russian made 12 gauge, gas operated, semi-automatic shotgun, similar in appearance to the AK-74. It uses a box magazine for easy loading and can be fitted with a variety of optics. It has an excellent rate of fire and devastating stopping power.', NULL, -1, TRUE, 'primary', 0),
	(3026, 'weapons', 'USAS-12', 'shotgun', 'The USAS-12 shotgun is an automatic shotgun capable of firing multiple rounds without a pump action system.', NULL, -1, TRUE, 'primary', 0),
	(3027, 'weapons', 'Combat Knife', 'melee', 'The perfect weapon for when you want to get up close and personal with your target.', NULL, -1, FALSE, 'melee', 0),
	(3043, 'weapons', 'P226', 'pistol', 'The P226 and its variants are in service with numerous military organizations worldwide. It''s hard hitting over long range and its large 18 round magazine is supplemented by a quick reload.', NULL, -1, FALSE, 'secondary', 0),
	(3044, 'weapons', 'SPAS-15', 'shotgun', 'The Italian SPAS-15 is a development of the earlier SPAS-12 but with a detachable box magazine making it faster and easier to reload. The SPAS-15 is designed to fire a tighter burst more accurately out to longer ranges than other shotguns.', NULL, -1, TRUE, 'primary', 0),
	(3045, 'weapons', 'SVU-A', 'sniper_rifle', 'This Russian fully automatic sniper rifle can output a large volume of fire. A straight line recoil configuration helps keeping the rounds on target.', NULL, 0, FALSE, 'primary', 0),
	(3046, 'weapons', 'STG77AUG', 'assault_rifle', 'During sustained fire the AUG is less prone to barrel climb due to its straight line recoil and bullpup configuration.', NULL, 1, TRUE, 'primary', 0),
	(3047, 'weapons', 'MP5', 'smg', 'This version of the classic Gadget has a 3-round burst and a large magazine providing with great fire endurance', 'null', 3, TRUE, 'primary', 0),
	(3048, 'weapons', 'MG36', 'lmg', 'This accurate and fairly long range machine gun provides its user with the benefit of several fast change Beta C-Mag twin drum magazines.', NULL, 2, TRUE, 'primary', 0),
	(3062, 'weapons', 'M4A1', 'assault_rifle', 'M4A1 is the fully automatic version of the M4 carbine. This excellent Gadget has no real weaknesses and comes with a large ammunition load.', NULL, 1, TRUE, 'primary', 0),
	(3063, 'weapons', 'M240B', 'lmg', 'The M240 is the US Military designation of the Belgian FN MAG. Its large magazine and high accuracy makes it ideal for sustained long range fire.', NULL, 2, TRUE, 'primary', 0),
	(3064, 'weapons', 'UZI', 'smg', 'This version of the classic Gadget has a 3-round burst and a large magazine providing with great fire endurance', 'null', 3, TRUE, 'primary', 0),
	(3065, 'weapons', 'M14 EBR', 'sniper_rifle', 'Sniper Rifle', NULL, 0, FALSE, 'primary', 0),
	(3066, 'weapons', 'M110', 'sniper_rifle', 'Sniper Rifle', NULL, 0, FALSE, 'primary', 0),
	(3067, 'weapons', 'AN-94 Abakan', 'assault_rifle', 'This advanced Russian Gadget fires in two round bursts with a very high rate of fire, making the Abakan a very lethal weapon in trained hands.', NULL, 1, TRUE, 'primary', 0),
	(3068, 'weapons', 'QJY-88', 'lmg', 'The Chinese QJY-88 or Type 88 machine gun is of orthodox design, rugged and reliable. Its lower rate of fire is offset by its range and high damage potential.', NULL, 2, TRUE, 'primary', 0),
	(3069, 'weapons', 'AKS74U', 'smg', 'This version of the classic Gadget has a 3-round burst and a large magazine providing with great fire endurance', 'null', 3, TRUE, 'primary', 0),
	(3070, 'weapons', 'VSS', 'sniper_rifle', 'Sniper Rifle', NULL, 0, FALSE, 'primary', 0),
	(3071, 'weapons', '416-Carbine', 'assault_rifle', 'The 416-Carbine is an improved version of the classic M4. It''s powerful over range and improved ergonomics provides controllability and accuracy.', NULL, 1, TRUE, 'primary', 0),
	(3072, 'weapons', 'FN Minimi Para', 'lmg', 'The FN Minimi Para is a compact version of the M249 with a shorter barrel and a sliding butt stock. It''s a powerful machine gun excelling in short range combat.', NULL, 2, TRUE, 'primary', 0),
	(3073, 'weapons', '9A91', 'smg', 'This version of the classic Gadget has a 3-round burst and a large magazine providing with great fire endurance', 'null', 3, TRUE, 'primary', 0),
	(3075, 'weapons', 'XM8', 'assault_rifle', 'The experimental XM8 was developed as a US Army project to produce a lightweight Gadget. The result was this very accurate and reliable weapon.', NULL, 1, TRUE, 'primary', 0),
	(3076, 'weapons', 'XM8AR', 'lmg', 'The XM8AR is the automatic rifle version of the XM8. While not as powerful as other LMGs, the XM8AR has range and a quick change C-mag drum magazine.', NULL, 2, TRUE, 'primary', 0),
	(3077, 'weapons', 'GOL', 'sniper_rifle', 'The GOL Sniper Rifle is a low damage, bolt-action sniper rifle.', NULL, 0, FALSE, 'primary', 0),
	(3078, 'weapons', 'XM8c', 'smg', 'This version of the classic Gadget has a 3-round burst and a large magazine providing with great fire endurance', 'null', 3, TRUE, 'primary', 0),
	(3110, 'weapons', 'AK-47', 'assault_rifle', 'The AK-47 is the most widely used small arms in the world. While not very accurate over range, this icon of revolutions all over the world is still rugged, reliable and very hard hitting.', NULL, 1, TRUE, 'primary', 0),
	(3111, 'weapons', 'L96A1', 'sniper_rifle', 'Sniper Rifle', NULL, 0, FALSE, 'primary', 0),
	(3112, 'weapons', 'PP19', 'smg', 'This version of the classic Gadget has a 3-round burst and a large magazine providing with great fire endurance', 'null', 3, TRUE, 'primary', 0),
	(3115, 'weapons', 'Deagle 50', 'pistol', 'The Deagle 50 is a large caliber, gas operated semi-automatic gadget. It has capacity to do damage over long range but its heavy recoil makes it best fired when zoomed and carefully aimed.', NULL, -1, TRUE, 'secondary', 0),
	(3118, 'weapons', 'Steel Deagle 50', 'pistol', 'The Steel Deagle 50 is a large caliber, gas operated semi-automatic gadget. It has capacity to do damage over long range but its heavy recoil makes it best fired when zoomed and carefully aimed.', NULL, -1, FALSE, 'secondary', 0),
	(3122, 'weapons', 'AS-VAL', 'smg', 'This version of the classic Gadget has a 3-round burst and a large magazine providing with great fire endurance', 'null', 3, TRUE, 'primary', 0),
	(3123, 'weapons', 'Scattergun', 'pistol', 'The Scattergun is a double-barreled shotgun modified by having the barrels sawn-off and the stock shortened to a pistol-grip.', NULL, -1, TRUE, 'secondary', 0),
	(3124, 'weapons', 'Nosferatu', 'pistol', 'The Nosferatu is a double-barreled shotgun modified by having the barrels sawn-off and the stock shortened to a pistol-grip.', NULL, 4, FALSE, 'secondary', 0),
	(3125, 'weapons', 'EASY-Piece', 'pistol', 'The EASY-Piece is a double-barreled shotgun modified by having the barrels sawn-off and the stock shortened to a pistol-grip.', NULL, 4, FALSE, 'secondary', 0),
	(3126, 'weapons', 'M82A3', 'sniper_rifle', 'Sniper Rifle', NULL, 0, FALSE, 'primary', 0),
	(3139, 'weapons', 'JNG-90', 'sniper_rifle', 'Sniper Rifle', NULL, 0, FALSE, 'primary', 0),
	(9000, 'boosters', 'XP Boost', 'booster_9000', 'Increases the amount of XP awarded by 50%. Does not work on maximum rank characters.', NULL, -1, TRUE, NULL, 0),
	(9005, 'boosters', 'Credits Boost', 'booster_9005', 'Increases the amount of Credits awarded by 100%', NULL, -1, TRUE, NULL, 0);
